name: Build and Deploy GitHub Pages

on:
  push:
    branches:
      - test-deploy

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
          VITE_KEYCLOAK_URL: https://key.jbnu.ac.kr
          VITE_KEYCLOAK_REALMS: JEduTools
          VITE_ADMIN_EMAIL: jedutools@gmail.com

      # - name: Create CNAME
      #   run: echo "jedutools.jbnu.ac.kr" > ./dist/CNAME

      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist